quiz/urls.py
'''
view all questions list
1. view question
2. take quiz
3. view quiz response
4. view question response and usage
5. view person details, i.e. how many quizzes they have taken, score
6. make quiz as AJAX
7. show top scorers in quiz
8. other quiz related stats 
'''

from django.conf.urls.defaults import *

urlpatterns = patterns('quiz.views',
	url(r'^questions/$', 'questions_list'),
	url(r'^question/(?P<id>\d+)/(?P<slug>[-\w]+)/$', 'question'),                       
        url(r'^quiz/(?P<id>\d+)/take/$', 'create_quiz'),
        url(r'^quiz/(?P<id>\d+)/report/$', 'report'),
        url(r'^quiz/(?P<id>\d+)/result/$', 'result'),
	url(r'^quiz/(?P<id>\d+)/$', 'quiz'),
	url(r'^quiz/(?P<id>\d+)/add-question$', 'add_question'),
	url(r'^quiz/new/$', 'new_quiz'),
        url(r'^add-answer/$', 'add_answer_choice'),
        url(r'^add-answer-post/$', 'add_answer_post'),
)

siteprofiles/urls.py
from django.conf.urls.defaults import *
from registration.forms import RegistrationForm
from registration.views import register
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('siteprofiles.views',
    url(r'^accounts/register/$', register, {'backend': 'siteprofiles.regbackend.RegBackend','form_class': RegistrationForm}, name='registration_register'),
    url(r'^login/$', 'login_user'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    # todo: why can't this be r'^profile/$' ?
    url(r'^profile/detail', 'view_profile'),
    url(r'^profile/edit/$','edit_profile'),
    url(r'^colleges/add/$', 'add_college'),
    url(r'^colleges/edit/(?P<id>\d+)/$', 'edit_college'),
    url(r'^colleges/detail/(?P<id>\d+)/$', 'view_college'),
    url(r'^company/add/$', 'add_company'),
    url(r'^company/edit/(?P<id>\d+)/$', 'edit_company'),
    url(r'^company/detail/(?P<id>\d+)/$', 'view_company'),
    url(r'^skills/add/$', 'add_skills'),
)

siteprofiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
#from django.db.models.signals import post_save

# Student Class relates default user model

class UserProfile(models.Model):
    user = models.OneToOneField(User,blank=True,related_name='colleger')
    first_name = models.CharField(max_length=32, null=True, blank=True)
    last_name = models.CharField(max_length=32, null=True, blank=True)
    mobile = models.CharField(max_length=12, null=True, blank=True)
    
    @property
    def is_student(self):
        try:
            self.student
            return True
        except Student.DoesNotExist:
            return False
    
class Address(models.Model):
    website = models.CharField(max_length=32, null=True, blank=True)
    blog = models.CharField(max_length=32, null=True, blank=True)
    address_line1 = models.CharField(max_length=32, null=True, blank=True)
    address_line2 = models.CharField(max_length=32, null=True, blank=True)
    address_line3 = models.CharField(max_length=32, null=True, blank=True)
    pincode = models.CharField(max_length=6,null=True, blank=True)
    area = models.CharField(max_length=32,null=True, blank=True)
    city = models.CharField(max_length=32,null=True, blank=True)
    state = models.CharField(max_length=32,null=True, blank=True)
    country = models.CharField(max_length=24,null=True, blank=True)
    phone = models.CharField(max_length=16,null=True, blank=True)
    
class College(models.Model):
    AFFILIATION = (
        ('anna_univ', 'Anna University'),
        ('deemed', 'Deemed'),
        ('autonomous', 'Autonomous'),
    )
    TYPE = (
        ('govt', 'Government'),
        ('govt_aid', 'Government-Aided'),
        ('private', 'Private'),
    )
    address = models.ForeignKey(Address,blank=True, null=True)
    name = models.CharField(max_length=64)
    ugc_cgpa = models.CharField(max_length=16, null=True, blank=True)
    ugc_grade = models.CharField(max_length=16, null=True, blank=True)
    established = models.CharField(max_length=16, null=True, blank=True)
    faculties = models.CharField(max_length=4, null=True, blank=True)
    affiliation = models.CharField(max_length=12, choices=AFFILIATION, null=True, blank=True)
    college_type = models.CharField(max_length=12, choices=TYPE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    
    def __unicode__(self):
        return u'%s' % (self.name)
    
class Skill(models.Model):
    skill = models.CharField(max_length=8, null=True, blank=True)
    skill_type = models.CharField(max_length=8, null=True, blank=True)
    
    def __unicode__(self):
        return u'%s' % (self.skill)

class Student(UserProfile):
    student = models.OneToOneField(UserProfile,related_name='student')
    skills = models.ManyToManyField(Skill, through='SkillSet')
    # todo: better field name
    study = models.ManyToManyField(College, through='Education')
    address = models.ForeignKey(Address,blank=True, null=True)
    passport = models.CharField(max_length=16, null=True, blank=True)
    resume = models.FileField(upload_to='resumes/%Y/%m/%d')
    dob = models.DateTimeField(null=True, blank=True)
    #avatar = models.FileField()
    #profile_photo = models.FileField()
    #tenth_certificate = models.FileField()
    #hsc_certificate = models.FileField()
    tenth_percentage = models.CharField(max_length=5, null=True, blank=True)
    hsc_percentage = models.CharField(max_length=5, null=True, blank=True)
 
class Professor(UserProfile):
    professor = models.OneToOneField(UserProfile,related_name='professor')
    working = models.ManyToManyField(College, through='Teaching', blank=True) 
    address = models.ForeignKey(Address,blank=True, null=True)
    prof_id = models.CharField(max_length=24, null=True, blank=True)

class Education(models.Model):
    YEAR_IN = (
        ('1', 'First Year'),
        ('2', 'Second Year'),
        ('3', 'Third Year'),
        ('4', 'Fourth Year'),
    )
    BRANCHES = (
        ('aero', 'Aeronautics'),
        ('auto', 'Automobile'),
        ('cs', 'Computer Science'),
        ('civ', 'Civil'),
        ('eee', 'Electrical and Electronics'),
        ('ece', 'Electronics and Communication'),
        ('it', 'Information Technology'),
        ('mech', 'Mechanical'),
        ('mecht', 'Mechatronics'),
    )
    college = models.ForeignKey(College, null=True, blank=True)
    student = models.ForeignKey(Student, null=True, blank=True)
    roll_no = models.CharField(max_length=24, null=True, blank=True)
    register_no = models.CharField(max_length=24, null=True, blank=True)
    doj = models.DateTimeField(null=True, blank=True)
    dop = models.DateTimeField(null=True, blank=True)
    year = models.CharField(max_length=2, choices=YEAR_IN, null=True, blank=True)
    branch = models.CharField(max_length=8, choices=BRANCHES, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    
class SkillSet(models.Model):
    RATING = (
        ('beginner', 'Beginner'),
        ('learner', 'Learner'),
        ('intermediate', 'Intermediate'),
        ('expert', 'Expert'),
    )
    skill = models.ForeignKey(Skill, null=True, blank=True)
    student = models.ForeignKey(Student, null=True, blank=True)
    rating = models.CharField(max_length=16, choices=RATING, null=True, blank=True)
    best_score = models.IntegerField(default=0)
    last_score = models.IntegerField(default=0)
    
class Teaching(models.Model):
    BRANCHES = (
        ('aero', 'Aeronautics'),
        ('auto', 'Automobile'),
        ('cs', 'Computer Science'),
        ('civ', 'Civil'),
        ('eee', 'Electrical and Electronics'),
        ('ece', 'Electronics and Communication'),
        ('it', 'Information Technology'),
        ('mech', 'Mechanical'),
        ('mecht', 'Mechatronics'),
    )
    SUBJECTS = (
        ('maths', 'Maths'),
        ('ed', 'Engineering Drawing'),
        ('atd', 'Applied Thermodynamics'),
        ('pe', 'Power Electronics'),
    )
    college = models.ForeignKey(College)
    professor = models.ForeignKey(Professor)
    date_of_joining = models.DateTimeField(null=True, blank=True)
    date_left = models.DateTimeField(null=True, blank=True)
    subject = models.CharField(max_length=2, choices=SUBJECTS, null=True, blank=True)
    branch = models.CharField(max_length=8, choices=BRANCHES, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    
class Company(models.Model):
    address = models.ForeignKey(Address, blank=True, null=True)
    name = models.CharField(max_length=48)
    head_count = models.CharField(max_length=8, blank=True, null=True)
    revenue = models.CharField(max_length=12, blank=True, null=True)
    headquarters = models.CharField(max_length=64) 
    established = models.CharField(max_length=4, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    
class Employer(UserProfile):
    employer = models.OneToOneField(UserProfile,related_name='employer') 
    address = models.ForeignKey(Address,blank=True, null=True)
    emp_id = models.CharField(max_length=24, null=True, blank=True)
    company = models.ForeignKey(Company, null=True, blank=True)
    
class Jobposting(models.Model):
    STATUS = (
        ('open', 'Open'),
        ('closed', 'Closed'),
    )
    postedby = models.ForeignKey(Employer)
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    description = models.TextField()
    status = models.CharField(max_length=8, choices=STATUS, null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    keywords = models.TextField(null=True, blank=True)
    posting_date = models.DateField(auto_now_add=True)

siteprofiles/views.py
from siteprofiles.forms import *
from django.contrib.auth.models import User
from django.forms.models import inlineformset_factory
from siteprofiles.models import *
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse 
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from django.shortcuts import redirect
 

# Function for Editing a User Profile
def edit_profile(request):
	CollegeFormSet = inlineformset_factory(Student,Education, extra=0,can_delete=False)
	SkillsFormSet = inlineformset_factory(Student,SkillSet, extra=0,can_delete=False, fields=('skill','rating'))
	uname = request.user
	st = Student.objects.get(user=uname)
	addr = st.address
	new_college = CollegeFormSet(prefix='college',instance=st)
	new_skill = SkillsFormSet(prefix='skills',instance=st)
	if request.method == 'POST':
	       	form = StudentForm(request.POST,request.FILES,instance=st)
		addr_form = AddressForm(request.POST, instance=addr)
		if 'add_college' in request.POST:
			cp = request.POST.copy()
			cp['college-TOTAL_FORMS'] = int(cp['college-TOTAL_FORMS'])+ 1
			new_college = CollegeFormSet(cp,prefix='college',instance=st)
        if 'add_skill' in request.POST:
			cpp = request.POST.copy()
			cpp['skills-TOTAL_FORMS'] = int(cpp['skills-TOTAL_FORMS'])+ 1
			new_skill = SkillsFormSet(cpp,prefix='skills',instance=st)
        elif 'submit' in request.POST:
			if addr_form.is_valid():
				addr = addr_form.save()
                        if 'resume' in request.FILES:
                                st = Student(resume=request.FILES['resume'])
                        if form.is_valid():
                                new_college = CollegeFormSet(request.POST,prefix='college',instance=st)
                                new_skill = SkillsFormSet(request.POST,prefix='skills',instance=st)
                                st = form.save(commit=False)
                                st.address = addr
                                st.save()
	                if new_college.is_valid():
				new_college.save()
                        if new_skill.is_valid():
                            new_skill.save()
                        return redirect('/profile/detail') 
	else:
		form = StudentForm(instance=st)
		addr_form = AddressForm(instance=addr)
	return render_to_response('profiles/edit_profile.html',{'form':form,'addr_form':addr_form,'college':new_college, 'skills':new_skill }, context_instance=RequestContext(request))

	                       
    	
# Function for Viewing a User Profile
def view_profile(request):
	uname = request.user
	try:
	    st = Student.objects.get(user=uname)
	    edu = Education.objects.filter(student=st)
	    skillset = SkillSet.objects.filter(student=st)
	    addr = st.address
	    return render_to_response('profiles/profile_detail.html', {'st':st,'addr':addr,'edu':edu, 'skillset':skillset}, context_instance=RequestContext(request))
	except:
	      emp = Employer.objects.get(user=uname)
	      addr = emp.address
	      return render_to_response('profiles/profile_detail.html', {'emp':emp,'addr':addr}, context_instance=RequestContext(request))
 	
def add_college(request):
	if request.method == 'POST':
		form = CollegeForm(request.POST)
		addr_form = AddressForm(request.POST)
		if addr_form.is_valid():
			addr = addr_form.save()
		if form.is_valid():
			colg = form.save(commit=False)
			colg.address = addr
			colg.save()
			id = str(colg.id)
		return redirect('/colleges/detail/'+id)
	else:
		form = CollegeForm()
		addr_form = AddressForm()
	return render_to_response('profiles/add_college.html',{'form':form,'addr_form':addr_form,'crud':'Add' },context_instance=RequestContext(request))
  
def edit_college(request,id):
        # todo: user get_object_or_404
	college = College.objects.get(pk=id)
	addr = college.address
	if request.method == 'POST':
		form = CollegeForm(request.POST, instance=college)
		addr_form = AddressForm(request.POST, instance=addr)
		if addr_form.is_valid():
			addr = addr_form.save()
		if form.is_valid():
			colg = form.save(commit=False)
			colg.address = addr
			colg.save()
			id = str(colg.id)
		return redirect('/colleges/detail/'+ id)
	else:
		form = CollegeForm(instance=college)
		addr_form = AddressForm(instance=addr)
	return render_to_response('profiles/add_college.html',{'form':form, 'addr_form':addr_form, 'crud':'Update' },context_instance=RequestContext(request))
	
# Function for Viewing a User Profile
def view_college(request,id):
        # todo: user get_object_or_404
	college = College.objects.get(pk=id)
	addr = college.address
 	return render_to_response('profiles/college_detail.html', {'college':college,'addr':addr}, context_instance=RequestContext(request))
 	
def add_company(request):
	if request.method == 'POST':
		form = CompanyForm(request.POST)
		addr_form = AddressForm(request.POST)
		if addr_form.is_valid():
			addr = addr_form.save()
		if form.is_valid():
			cmpny = form.save(commit=False)
			cmpny.address = addr
			cmpny.save()
			id = str(cmpny.id)
		return redirect('/company/detail/'+id)
	else:
		form = CompanyForm()
		addr_form = AddressForm()
	return render_to_response('profiles/add_company.html',{'form':form,'addr_form':addr_form,'crud':'Add' },context_instance=RequestContext(request))

def edit_company(request,id):
        # todo: user get_object_or_404
	company = Company.objects.get(pk=id)
	addr = company.address
	if request.method == 'POST':
		form = CompanyForm(request.POST, instance=company)
		addr_form = AddressForm(request.POST, instance=addr)
		if addr_form.is_valid():
			addr = addr_form.save()
		if form.is_valid():
			cmpny = form.save(commit=False)
			cmpny.address = addr
			cmpny.save()
			id = str(cmpny.id)
		return redirect('/company/detail/'+ id)
	else:
		form = CompanyForm(instance=company)
		addr_form = AddressForm(instance=addr)
	return render_to_response('profiles/add_college.html',{'form':form, 'addr_form':addr_form, 'crud':'Update' },context_instance=RequestContext(request))
	
# Function for Viewing a User Profile
def view_company(request,id):
        # todo: user get_object_or_404
	company = Company.objects.get(pk=id)
	addr = company.address
 	return render_to_response('profiles/company_detail.html', {'company':company,'addr':addr}, context_instance=RequestContext(request))
 	
def add_skills(request):
	skills = Skill.objects.all()
	if request.method == 'POST':
		form = SkillForm(request.POST)
		if form.is_valid():
			skill = form.save()
		#return redirect('/company/detail/'+id)
	else:
		form = SkillForm()
	return render_to_response('profiles/add_skill.html',{'form':form,'skilldetails':skills },context_instance=RequestContext(request))


# Separate function for Login. (May be remove it later or modify it)
def login_user(request):
    state = "Please log in below..."
    username = password = ''
    if request.POST:
        # todo: I think username and password can be obtained from form dict
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                state = "You're successfully logged in!"
                return redirect('siteprofiles.views.view_profile') 
            else:
                state = "Your account is not active, please contact the site admin."
        else:
            state = "Your username and/or password were incorrect."
    return render_to_response('siteprofiles.views.login_user',{'state':state, 'username': username}, RequestContext(request))

siteprofiles/templates/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <link rel="stylesheet" href="/style.css" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
    <title>{% block title %}User test{% endblock %}</title>
    	<style type="text/css">
    	div.tabscontainer{
		    margin:15px 0px;
		}
		div.profile-content {
			display: block;
			width:400px;
			padding:10px;
		}
		
		div.profile-field-label {
			width:120px;
			padding:5px;
			display:inline-block
		}
		 
		div.profile-field-value {
			width:250px;
			display:inline-block;
			padding:5px;
		}
		
		div.tabscontainer div.tabs{
		    list-style: none;
		    width: 160px;
		    cursor: pointer;
		    float:left;
		    margin-top: 150px;
		    margin-left: 600px;
		    z-index: 2;
		}
		 
		div.tabscontainer div.curvedContainer{
		    margin-left: 159px;
		    border:1px solid #7c7c77;
		    min-height:400px;
		    -moz-border-radius: 13px;
		    border-radius: 13px;
		}
		 
		div.tabscontainer div.curvedContainer .tabcontent{
		    display:none;
		    padding:20px;
		    font-size:12px;
		    font-family: "CenturyGothicRegular", "Century Gothic", Arial, Helvetica, sans-serif;
		}
		 
		div.tabs div.tab{
		    display: block;
		    height: 48px;
		    background: #eeeeea;
		    border: #d6d6d2 solid 1px;
		    border-top: none;
		    position: relative;
		    color: #73736b;
		}
		 
		div.tabs div.link{
		    padding-left: 20px;
		    padding-top:20px;
		    font-family: "CenturyGothicRegular", "Century Gothic", Arial, Helvetica, sans-serif;
		    font-size: 14px;
		}
		 
		div.tabs div.tab.selected{
		    border-right-color: #aeaeaa;
		}
		 
		div.tabs div.tab.selected{
		    background: url(menuSelBack.png) repeat-x;
		    border-right-color: #7c7c77;
		}
		 
		div.tabs div.tab.first{
		    border-top: #dbdbb7 solid 1px;
		    -moz-border-radius-topleft: 13px;
		    border-top-left-radius: 13px;
		}
		 
		div.tabs div.tab.last{
		    -moz-border-radius-bottomleft: 13px;
		    border-bottom-left-radius: 13px;
		}
		 
		div.tabs div.tab div.arrow{
		    position: absolute;
		    background: url(homeSelArrow.png) no-repeat;
		    height: 58px;
		    width: 17px;
		    left: 100%;
		    top: 0px;
		    display: none;
		}
		 
		div.tabs div.tab.selected div.arrow{
		    display: block;
		}
		</style>
		
		<script type="text/javascript">
		$(document).ready(function() {
	    	$(".tabs .tab[id^=tab_menu]").click(function() {
	        var curMenu=$(this);
	        $(".tabs .tab[id^=tab_menu]").removeClass("selected");
	        curMenu.addClass("selected");
	 
	        var index=curMenu.attr("id").split("tab_menu_")[1];
	        $(".curvedContainer .tabcontent").css("display","none");
	        $(".curvedContainer #tab_content_"+index).css("display","block");
	   		});
	   		$(function() {
           		$("#id_dob").datepicker({ dateFormat: 'dd/mm/yy' });
           		$("#id_college-0-doj").datepicker({ dateFormat: 'dd/mm/yy' });
           		$("#id_college-0-dop").datepicker({ dateFormat: 'dd/mm/yy' });
        	});
		});
		</script>
</head>

<body>
    <div id="header"style="width:100%;height:50px">
        {% block header %}
	{% if user.is_authenticated %}
	{% trans "Logged in" %}: {{ user.username }} 
	(<a href="{% url auth_logout %}">{% trans "Log out" %}</a> | 
	<a href="{% url auth_password_change %}">{% trans "Change password" %}</a>)
	{% else %}
	<div id="login-form" style="float:right;padding:10px">
	<form action="/login/" method="post" accept-charset="utf-8">{% csrf_token %}
		<label for="username">Username</label><input type="text" name="username" value="" id="username" />
		<label for="password">Password</label><input type="password" name="password" value="" id="password" />
		<input type="submit" value="Login">
	</form>
	</div>
	{% endif %}
        {% endblock %}
    </div>
	<div id="navigation">
        {% block navigation %}{% endblock %}
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="footer">
        {% block footer %}
        {% endblock %}
    </div>
</body>

</html>

siteprofiles/templates/registration_base.html
<div class="red">
{% if form.non_field_errors %}
{{ form.non_field_errors }}
{% endif %}
</div>
 <div class="tabscontainer">
     <div class="tabs">
         <div class="tab selected first" id="tab_menu_1">
             <div class="link">Student</div>
             <div class="arrow"></div>
         </div>
         <div class="tab" id="tab_menu_2">
             <div class="link">Professor</div>
             <div class="arrow"></div>
         </div>
          <div class="tab last" id="tab_menu_3">
             <div class="link">Employer</div>
             <div class="arrow"></div>
         </div>
    </div>
    <div class="curvedContainer">
        <div class="tabcontent" id="tab_content_1" style="display:block">
	        <form method="post" action="/accounts/register/" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
			   <div id="student-registration" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:582px">
				{% for field in form %}
				<div style="width:400px;padding:15px;">
			            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
						<div style="display:inline">{{ field }}</div>
				</div>
						{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
						{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
				{% endfor %}
				<input type="hidden" name="persontype" value="student"/>
				<input type="submit" value="Register" class="submit" style="width:100px;margin:0px auto;display:block;height:32px;">
				</div>
			</form>
        </div>
        <div class="tabcontent" id="tab_content_2">
        	        <form method="post" action="/accounts/register/" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
			   <div id="student-registration" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:582px">
				{% for field in form %}
				<div style="width:400px;padding:15px;">
			            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
						<div style="display:inline">{{ field }}</div>
				</div>
						{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
						{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
				{% endfor %}
				<input type="hidden" name="persontype" value="professor"/>
				<input type="submit" value="Register as Professor" class="submit" style="width:140px;margin:0px auto;display:block;height:32px;">
				</div>
			</form>
        </div>
        <div class="tabcontent" id="tab_content_3">
        	        <form method="post" action="/accounts/register/" class="accountForm marginTop">{% csrf_token %}<!-- Added due to internal url-->
			   <div id="student-registration" style="width:400px;background-color:#aaa;margin-top:30px;margin-left:582px">
				{% for field in form %}
				<div style="width:400px;padding:15px;">
			            <div class="hint {%if field.field.required %} bold {% endif %}" style="clear:both;width:40%;display:inline-block">{{ field.label_tag }}</div>
						<div style="display:inline">{{ field }}</div>
				</div>
						{% if field.help_text %}<span>{{ field.help_text }}</span>{% endif %}
						{% if field.errors %}<span>{{ field.errors }}</span>{% endif %}
				{% endfor %}
				<input type="hidden" name="persontype" value="employer"/>
				<input type="submit" value="Register as Employer" class="submit" style="width:140px;margin:0px auto;display:block;height:32px;">
				</div>
			</form>
        </div>

        
        
        </div>
    </div>
</div>